name: dart_autotrader
description: An Autotrader API library for dart and flutter developers
version: 1.0.0
homepage: https://github.com/point-source/dart_autotrader

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  chopper: ^6.0.0
  dart_mappable: ^2.0.0-dev.6
  intl: ^0.18.0

dev_dependencies:
  build_runner: ^2.3.3
  chopper_generator: ^6.0.0
  dart_code_metrics: ^5.3.0
  dart_mappable_builder: ^2.0.0-dev.6
  lints: ^2.0.0
  test: ^1.16.0
