name: dart_autotrader
description: An Autotrader API library for dart and flutter developers
version: 2.0.0
homepage: https://github.com/point-source/dart_autotrader

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  chopper: ^7.1.0
  dart_mappable: ^4.2.0
  intl: ^0.19.0

dev_dependencies:
  build_runner: ^2.3.3
  chopper_generator: ^7.1.0
  dart_mappable_builder: ^4.2.0
  lints: ^3.0.0
  test: ^1.16.0
